# Generated by Django 5.1.3 on 2024-11-21 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0003_alter_course_unique_together_course_shortname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('order_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModuleLearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('order_by', models.IntegerField(default=0)),
                ('course_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crafter.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModuleLearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('learning_outcome', models.TextField(blank=True, default=None, null=True)),
                ('order_by', models.IntegerField(default=0)),
                ('course_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crafter.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('prompt_used', models.TextField(blank=True, default=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafter.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crafter.courseversion'),
        ),
        migrations.CreateModel(
            name='CourseVersionLearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('learning_outcome', models.TextField(blank=True, default=None, null=True)),
                ('order_by', models.IntegerField(default=0)),
                ('course_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crafter.courseversion')),
            ],
        ),
    ]
