# Generated by Django 5.1.3 on 2024-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0004_coursemodule_coursemodulelearningactivity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModuleLearningOutcomes',
            new_name='CourseModuleLearningOutcome',
        ),
        migrations.RenameModel(
            old_name='CourseVersionLearningOutcomes',
            new_name='CourseVersionLearningOutcome',
        ),
    ]
