# Generated by Django 5.1.3 on 2024-11-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0005_rename_coursemodulelearningoutcomes_coursemodulelearningoutcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='course_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursemodules', to='crafter.courseversion'),
        ),
        migrations.AlterField(
            model_name='coursemodulelearningactivity',
            name='course_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursemodulelas', to='crafter.coursemodule'),
        ),
        migrations.AlterField(
            model_name='coursemodulelearningoutcome',
            name='course_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursemodulelos', to='crafter.coursemodule'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseresources', to='crafter.course'),
        ),
        migrations.AlterField(
            model_name='courseversion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseversions', to='crafter.course'),
        ),
        migrations.AlterField(
            model_name='courseversionlearningoutcome',
            name='course_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseversionlos', to='crafter.courseversion'),
        ),
    ]
