# Generated by Django 5.1.3 on 2024-11-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0006_alter_coursemodule_course_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseversion',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
