# Generated by Django 5.1.3 on 2024-11-21 21:22

import crafter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0007_courseversion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=crafter.models.user_directory_path),
        ),
    ]
