# Generated by Django 5.1.3 on 2024-11-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0008_alter_courseresource_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('course_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulequestions', to='crafter.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleResponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('module_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionresponses', to='crafter.modulequestion')),
            ],
        ),
    ]
