# Generated by Django 5.1.3 on 2024-11-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0009_modulequestion_moduleresponseoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulequestions', to='crafter.coursemodule'),
        ),
        migrations.AlterField(
            model_name='moduleresponseoption',
            name='module_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionresponses', to='crafter.modulequestion'),
        ),
    ]
